/*=============== THÔNG BÁO ===============*/
document.write('<body onload="thongbaopopup()">');
document.write('    <style>');
document.write('        .tbpopup .tboverlay {');
document.write('            position: fixed;');
document.write('            top: 0px;');
document.write('            left: 0px;');
document.write('            width: 100vw;');
document.write('            height: 100vh;');
document.write('            background: rgba(0, 0, 0, 0.7);');
document.write('            z-index: 1;');
document.write('            display: none;');
document.write('        }');
document.write('        ');
document.write('        .tbpopup .tbcontent {');
document.write('            position: absolute;');
document.write('            top: 50%;');
document.write('            left: 50%;');
document.write('            transform: translate(-50%, -50%) scale(0);');
document.write('            background: #191919;');
document.write('            max-width: 500px;');
document.write('            z-index: 2;');
document.write('            text-align: center;');
document.write('            padding: 20px;');
document.write('            box-sizing: border-box;');
document.write('            font-family: "Open Sans", sans-serif;');
document.write('            border-radius: 20px;');
document.write('            display: block;');
document.write('            position: fixed;');
document.write('            box-shadow: 0px 0px 10px #111;');
document.write('        }');
document.write('        ');
document.write('        @media (max-width: 700px) {');
document.write('            .tbpopup .tbcontent {');
document.write('                width: 90%;');
document.write('            }');
document.write('        }');
document.write('        ');
document.write('        .tbpopup .tbclose-btn {');
document.write('            cursor: pointer;');
document.write('            position: absolute;');
document.write('            right: 20px;');
document.write('            top: 20px;');
document.write('            width: 35px;');
document.write('            height: 35px;');
document.write('            color: #fff;');
document.write('            font-size: 30px;');
document.write('            font-weight: 600;');
document.write('            line-height: 35px;');
document.write('            text-align: center;');
document.write('            border-radius: 50%;');
document.write('        }');
document.write('        ');
document.write('        .tbpopup.active .tboverlay {');
document.write('            display: block;');
document.write('        }');
document.write('        ');
document.write('        .tbpopup.active .tbcontent {');
document.write('            transition: all 300ms ease-in-out;');
document.write('            transform: translate(-50%, -50%) scale(1);');
document.write('        }');
document.write('        ');
document.write('        .tbbuttom {');
document.write('            background: #00cc00;');
document.write('            color: fff');
document.write('        }');
document.write('    </style>');
document.write('    ');
document.write('    <div class="tbpopup" id="tbpopup-1">');
document.write('        <div class="tboverlay"></div>');
document.write('        <div class="tbcontent">');
document.write('            <div class="tbclose-btn" onclick="thongbaopopup()">×</div>');
document.write('            <div style="font-size:30px;font-weight:bold; margin-top:-10px;">Thông báo !</div>');
document.write('             <div style="border-bottom: 1px solid #e0e0e0; margin-bottom: 20px;"></div>');
document.write('            <p style="font-size:27px; ">Chào Mừng Bạn Đã Ghé Trang Web Của Tôi <img src="https://cdn.discordapp.com/emojis/1138666477826887700.gif?size=44&quality=lossless" style="height: 30px;" target="_blank"  style=" color:blue; font-weight: bold;"> </a></p>');
document.write('            <p style="font-size:20px;">🔥 Website Được Tạo Bởi<a href="https://www.facebook.com/profile.php?id=61550315515074" target="_blank"  style=" color:blue; font-weight: bold;"> Nguyễn Hoàng Long</a> <img src="https://cdn.discordapp.com/emojis/1138666761965809664.gif?size=44&quality=lossless" style="height: 30px;" target="_blank"  style=" color:blue; font-weight: bold;"> </a></p>');
document.write('            </div>');
document.write('    </div>');
document.write('    ');
document.write('    <script>');
document.write('        function thongbaopopup() {');
document.write('            document.getElementById("tbpopup-1").classList.toggle("active");');
document.write('        }');
document.write('    </script>  ');
